name: Build
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19
        cache: sbt
    - name: Build
      run: sbt -v +assembly
    - uses: softprops/action-gh-release@v1
      with:
        files: target/scala-*/uuverifiers/catra-assembly-*.jar
