name: Build
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19
        cache: sbt
    - name: Build
      run: sbt -v +assembly
    - uses: actions/upload-artifact@v3
      with:
        name: catra
        path: target/scala-*/uuverifiers/catra-assembly-*.jar
